### ISSUE TITLE
Add Trimgalore bundle to Era7 Bundles

### ISSUE THREAD

**Issue by marina-manrique** [era7bio/bundles#22]
@eparejatobes @laughedelic I would need TrimGalore and Cutadapt for a project (`microixo`). The bundle to install them are already done [https://github.com/ohnosequences-bundles/trimgalore/blob/make/install/src/main/scala/trimgalore.scala](https://github.com/ohnosequences-bundles/trimgalore/blob/make/install/src/main/scala/trimgalore.scala), [https://github.com/ohnosequences-bundles/cutadapt/blob/master/src/main/scala/cutadapt.scala](https://github.com/ohnosequences-bundles/cutadapt/blob/master/src/main/scala/cutadapt.scala)

I'm not sure whether the one for `TrimGalore` is tested because the branch is not merged into master. My questions are:
- It is fine for you that I test and merge the `TrimGalore` into master and I publish the artifacts for both of them? In that case should I  make a release?
- Once `TrimGalore` and `Cutadapt` are released can I add them here in the `std.scala`? if so, should I publish and make a release here as well?

**Comment by laughedelic** [comment]
Well, looking at the code, they need to be updated to the current statika. About the rest of the workflow:
- once you get a bundle that compiles on its own, publish a snapshot
- add this snapshot dependency to `era7bio/bundles` and add bundle to `std`, etc. as the rest of bundles
- in `era7bio/bundles` add a test for it
- publish, run the test
- once it works, you can make a release of the bundle and a release of the `era7bio/bundles` (but normally you would add several bundles and make a common release with them)

**Comment by laughedelic** [comment]
About cudapt's code. It's very easy, just change the install method to
```scala
def instructions: AnyInstructions = cmd("pip")("install", "cutadapt")
```

Are you sure that it depends on `cdevel`, I thought `pip` is some python installer..

**Comment by laughedelic** [comment]
About Trimgalore, a good example of a similar bundle is [fastqc](https://github.com/ohnosequences-bundles/fastqc/blob/master/src/main/scala/fastqc.scala) (without the `makeExecutable` step, I guess). Take a look at the code there.

**Comment by marina-manrique** [comment]
:+1:  Thanks!

**Comment by marina-manrique** [comment]
I was updating `TrimGalore` bundle to Statika `2.0.0-M4` and I found out that I have to do the same with `cutadapt` and  `cdevel`

So I'm updating all of them

**Comment by laughedelic** [comment]
@marina-manrique [cdevel v0.3.0](https://github.com/ohnosequences-bundles/cdevel/releases/tag/v0.3.0) is up to date

**Comment by marina-manrique** [comment]
:+1:

**Comment by marina-manrique** [comment]
I'm making a new release of `era7bio/bundles` which includes `trimgalore` and `cutadapt` bundles

**Comment by eparejatobes** [comment]
done, closing
